export const browserCoreExamples = [
  "panda browser status",
  "panda browser start",
  "panda browser stop",
  "panda browser tabs",
  "panda browser open https://example.com",
  "panda browser focus abcd1234",
  "panda browser close abcd1234",
  "panda browser screenshot",
  "panda browser screenshot --full-page",
  "panda browser screenshot --ref 12",
  "panda browser snapshot",
  "panda browser snapshot --format aria --limit 200",
  "panda browser snapshot --efficient",
  "panda browser snapshot --labels",
];

export const browserActionExamples = [
  "panda browser navigate https://example.com",
  "panda browser resize 1280 720",
  "panda browser click 12 --double",
  'panda browser type 23 "hello" --submit',
  "panda browser press Enter",
  "panda browser hover 44",
  "panda browser drag 10 11",
  "panda browser select 9 OptionA OptionB",
  "panda browser upload /tmp/file.pdf",
  'panda browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "panda browser dialog --accept",
  'panda browser wait --text "Done"',
  "panda browser evaluate --fn '(el) => el.textContent' --ref 7",
  "panda browser console --level error",
  "panda browser pdf",
];
