#!/usr/bin/env python3
"""批量替换环境变量引用"""
import os
import re
from pathlib import Path

# 环境变量映射表
ENV_VAR_MAPPINGS = {
    "PANDABOT_STATE_DIR": "PANDA_STATE_DIR",
    "PANDA_STATE_DIR": "PANDA_STATE_DIR",
    "PANDABOT_CONFIG_PATH": "PANDA_CONFIG_PATH",
    "PANDA_CONFIG_PATH": "PANDA_CONFIG_PATH",
    "PANDABOT_GATEWAY_TOKEN": "PANDA_GATEWAY_TOKEN",
    "PANDABOT_GATEWAY_PASSWORD": "PANDA_GATEWAY_PASSWORD",
    "PANDABOT_GATEWAY_PORT": "PANDA_GATEWAY_PORT",
    "PANDABOT_SKIP_CHANNELS": "PANDA_SKIP_CHANNELS",
    "PANDABOT_SKIP_GMAIL_WATCHER": "PANDA_SKIP_GMAIL_WATCHER",
    "PANDABOT_SKIP_CRON": "PANDA_SKIP_CRON",
    "PANDABOT_SKIP_CANVAS_HOST": "PANDA_SKIP_CANVAS_HOST",
    "PANDABOT_SKIP_BROWSER_CONTROL_SERVER": "PANDA_SKIP_BROWSER_CONTROL_SERVER",
    "PANDABOT_LIVE_TEST": "PANDA_LIVE_TEST",
    "PANDABOT_LIVE_GATEWAY": "PANDA_LIVE_GATEWAY",
    "PANDABOT_TEST_FAST": "PANDA_TEST_FAST",
    "PANDABOT_TEST_HOME": "PANDA_TEST_HOME",
    "PANDABOT_BRIDGE_ENABLED": "PANDA_BRIDGE_ENABLED",
    "PANDABOT_BRIDGE_HOST": "PANDA_BRIDGE_HOST",
    "PANDABOT_BRIDGE_PORT": "PANDA_BRIDGE_PORT",
    "PANDABOT_CANVAS_HOST_PORT": "PANDA_CANVAS_HOST_PORT",
    "PANDABOT_PROFILE": "PANDA_PROFILE",
    "PANDABOT_NIX_MODE": "PANDA_NIX_MODE",
    "PANDA_NIX_MODE": "PANDA_NIX_MODE",
    "PANDABOT_LOAD_SHELL_ENV": "PANDA_LOAD_SHELL_ENV",
    "PANDABOT_DEFER_SHELL_ENV_FALLBACK": "PANDA_DEFER_SHELL_ENV_FALLBACK",
    "PANDABOT_SHELL_ENV_TIMEOUT_MS": "PANDA_SHELL_ENV_TIMEOUT_MS",
    "PANDABOT_VERSION": "PANDA_VERSION",
    "PANDABOT_AGENT_DIR": "PANDA_AGENT_DIR",
    "PANDABOT_SYSTEMD_UNIT": "PANDA_SYSTEMD_UNIT",
    "PANDABOT_LAUNCHD_LABEL": "PANDA_LAUNCHD_LABEL",
    "PANDABOT_DISABLE_BONJOUR": "PANDA_DISABLE_BONJOUR",
    "PANDABOT_UPDATE_IN_PROGRESS": "PANDA_UPDATE_IN_PROGRESS",
    "PANDABOT_PATH_BOOTSTRAPPED": "PANDA_PATH_BOOTSTRAPPED",
    "PANDABOT_E2E_MODELS": "PANDA_E2E_MODELS",
    "PANDABOT_OAUTH_DIR": "PANDA_OAUTH_DIR",
    "PANDABOT_TTS_PREFS": "PANDA_TTS_PREFS",
    "PANDABOT_BUNDLED_VERSION": "PANDA_BUNDLED_VERSION",
    "PANDABOT_BUNDLED_PLUGINS_DIR": "PANDA_BUNDLED_PLUGINS_DIR",
    "PANDABOT_DIAGNOSTICS": "PANDA_DIAGNOSTICS",
    "PANDABOT_PLUGIN_CATALOG_PATHS": "PANDA_PLUGIN_CATALOG_PATHS",
    "PANDABOT_MPM_CATALOG_PATHS": "PANDA_MPM_CATALOG_PATHS",
    "PANDABOT_RAW_STREAM": "PANDA_RAW_STREAM",
    "PANDABOT_DEBUG_MEMORY_EMBEDDINGS": "PANDA_DEBUG_MEMORY_EMBEDDINGS",
    "PANDABOT_NODE_EXEC_HOST": "PANDA_NODE_EXEC_HOST",
    "PANDABOT_CONTROL_UI_BASE_PATH": "PANDA_CONTROL_UI_BASE_PATH",
    "PANDABOT_ASSISTANT_NAME": "PANDA_ASSISTANT_NAME",
    "PANDABOT_ASSISTANT_AVATAR": "PANDA_ASSISTANT_AVATAR",
    "PANDABOT_LIVE_GATEWAY_ZAI_FALLBACK": "PANDA_LIVE_GATEWAY_ZAI_FALLBACK",
    "PANDABOT_LIVE_GATEWAY_PROVIDERS": "PANDA_LIVE_GATEWAY_PROVIDERS",
    "PANDABOT_LIVE_CLI_BACKEND": "PANDA_LIVE_CLI_BACKEND",
    "PANDABOT_LIVE_CLI_BACKEND_IMAGE_PROBE": "PANDA_LIVE_CLI_BACKEND_IMAGE_PROBE",
    "PANDABOT_LIVE_CLI_BACKEND_RESUME_PROBE": "PANDA_LIVE_CLI_BACKEND_RESUME_PROBE",
    "PANDABOT_LIVE_MODELS": "PANDA_LIVE_MODELS",
    "PANDABOT_LIVE_REQUIRE_PROFILE_KEYS": "PANDA_LIVE_REQUIRE_PROFILE_KEYS",
    "PANDABOT_LIVE_SETUP_TOKEN": "PANDA_LIVE_SETUP_TOKEN",
    "PANDABOT_LIVE_SETUP_TOKEN_VALUE": "PANDA_LIVE_SETUP_TOKEN_VALUE",
    "PANDABOT_LIVE_SETUP_TOKEN_PROFILE": "PANDA_LIVE_SETUP_TOKEN_PROFILE",
    "PANDABOT_LIVE_SETUP_TOKEN_MODEL": "PANDA_LIVE_SETUP_TOKEN_MODEL",
    "PANDABOT_LIVE_BROWSER_CDP_URL": "PANDA_LIVE_BROWSER_CDP_URL",
    "PANDABOT_TELEGRAM_ENABLE_AUTO_SELECT_FAMILY": "PANDA_TELEGRAM_ENABLE_AUTO_SELECT_FAMILY",
    "__PANDABOT_VERSION__": "__PANDA_VERSION__",
    "__PANDABOT_CONTROL_UI_BASE_PATH__": "__PANDA_CONTROL_UI_BASE_PATH__",
    "__PANDABOT_ASSISTANT_NAME__": "__PANDA_ASSISTANT_NAME__",
    "__PANDABOT_ASSISTANT_AVATAR__": "__PANDA_ASSISTANT_AVATAR__",
}

def process_file(file_path):
    """处理单个文件"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original_content = content
        
        # 执行替换
        for old_var, new_var in ENV_VAR_MAPPINGS.items():
            content = content.replace(old_var, new_var)
        
        # 如果有变化则写回文件
        if content != original_content:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✓ {file_path}")
            return 1
        return 0
    except Exception as e:
        print(f"✗ {file_path}: {e}")
        return 0

def main():
    base_dir = Path.cwd()
    dirs_to_process = ['src', 'test', 'ui']
    extensions = ['.ts', '.js', '.tsx']
    
    total_files = 0
    updated_files = 0
    
    print("开始替换环境变量...")
    
    for dir_name in dirs_to_process:
        dir_path = base_dir / dir_name
        if not dir_path.exists():
            continue
            
        for ext in extensions:
            for file_path in dir_path.rglob(f'*{ext}'):
                if file_path.is_file():
                    total_files += 1
                    updated_files += process_file(file_path)
    
    print(f"\n完成! 共处理 {total_files} 个文件, 更新了 {updated_files} 个文件")

if __name__ == '__main__':
    main()
