#!/usr/bin/env bash
# 批量替换环境变量引用脚本

set -e

echo "开始替换环境变量..."

# 定义替换函数
replace_env() {
    local old_var="$1"
    local new_var="$2"
    echo "替换 $old_var -> $new_var"
    
    # 使用 grep 查找并替换
    find src test ui -name "*.ts" -type f 2>/dev/null | while read file; do
        if grep -q "$old_var" "$file" 2>/dev/null; then
            sed -i '' "s/${old_var}/${new_var}/g" "$file"
        fi
    done
}

# 执行替换
replace_env "CLAWDBOT_STATE_DIR" "PANDA_STATE_DIR"
replace_env "MOLTBOT_STATE_DIR" "PANDA_STATE_DIR"
replace_env "CLAWDBOT_CONFIG_PATH" "PANDA_CONFIG_PATH"
replace_env "MOLTBOT_CONFIG_PATH" "PANDA_CONFIG_PATH"
replace_env "CLAWDBOT_GATEWAY_TOKEN" "PANDA_GATEWAY_TOKEN"
replace_env "CLAWDBOT_GATEWAY_PASSWORD" "PANDA_GATEWAY_PASSWORD"
replace_env "CLAWDBOT_GATEWAY_PORT" "PANDA_GATEWAY_PORT"
replace_env "CLAWDBOT_SKIP_CHANNELS" "PANDA_SKIP_CHANNELS"
replace_env "CLAWDBOT_SKIP_GMAIL_WATCHER" "PANDA_SKIP_GMAIL_WATCHER"
replace_env "CLAWDBOT_SKIP_CRON" "PANDA_SKIP_CRON"
replace_env "CLAWDBOT_SKIP_CANVAS_HOST" "PANDA_SKIP_CANVAS_HOST"
replace_env "CLAWDBOT_SKIP_BROWSER_CONTROL_SERVER" "PANDA_SKIP_BROWSER_CONTROL_SERVER"
replace_env "CLAWDBOT_LIVE_TEST" "PANDA_LIVE_TEST"
replace_env "CLAWDBOT_LIVE_GATEWAY" "PANDA_LIVE_GATEWAY"
replace_env "CLAWDBOT_TEST_FAST" "PANDA_TEST_FAST"
replace_env "CLAWDBOT_TEST_HOME" "PANDA_TEST_HOME"
replace_env "CLAWDBOT_BRIDGE_ENABLED" "PANDA_BRIDGE_ENABLED"
replace_env "CLAWDBOT_BRIDGE_HOST" "PANDA_BRIDGE_HOST"
replace_env "CLAWDBOT_BRIDGE_PORT" "PANDA_BRIDGE_PORT"
replace_env "CLAWDBOT_CANVAS_HOST_PORT" "PANDA_CANVAS_HOST_PORT"
replace_env "CLAWDBOT_PROFILE" "PANDA_PROFILE"
replace_env "CLAWDBOT_NIX_MODE" "PANDA_NIX_MODE"
replace_env "MOLTBOT_NIX_MODE" "PANDA_NIX_MODE"
replace_env "CLAWDBOT_LOAD_SHELL_ENV" "PANDA_LOAD_SHELL_ENV"
replace_env "CLAWDBOT_DEFER_SHELL_ENV_FALLBACK" "PANDA_DEFER_SHELL_ENV_FALLBACK"
replace_env "CLAWDBOT_SHELL_ENV_TIMEOUT_MS" "PANDA_SHELL_ENV_TIMEOUT_MS"
replace_env "CLAWDBOT_VERSION" "PANDA_VERSION"
replace_env "CLAWDBOT_AGENT_DIR" "PANDA_AGENT_DIR"
replace_env "CLAWDBOT_SYSTEMD_UNIT" "PANDA_SYSTEMD_UNIT"
replace_env "CLAWDBOT_LAUNCHD_LABEL" "PANDA_LAUNCHD_LABEL"
replace_env "CLAWDBOT_DISABLE_BONJOUR" "PANDA_DISABLE_BONJOUR"
replace_env "CLAWDBOT_UPDATE_IN_PROGRESS" "PANDA_UPDATE_IN_PROGRESS"
replace_env "CLAWDBOT_PATH_BOOTSTRAPPED" "PANDA_PATH_BOOTSTRAPPED"
replace_env "CLAWDBOT_E2E_MODELS" "PANDA_E2E_MODELS"
replace_env "CLAWDBOT_OAUTH_DIR" "PANDA_OAUTH_DIR"
replace_env "CLAWDBOT_TTS_PREFS" "PANDA_TTS_PREFS"
replace_env "CLAWDBOT_BUNDLED_VERSION" "PANDA_BUNDLED_VERSION"
replace_env "CLAWDBOT_BUNDLED_PLUGINS_DIR" "PANDA_BUNDLED_PLUGINS_DIR"
replace_env "CLAWDBOT_DIAGNOSTICS" "PANDA_DIAGNOSTICS"
replace_env "CLAWDBOT_PLUGIN_CATALOG_PATHS" "PANDA_PLUGIN_CATALOG_PATHS"
replace_env "CLAWDBOT_MPM_CATALOG_PATHS" "PANDA_MPM_CATALOG_PATHS"
replace_env "CLAWDBOT_RAW_STREAM" "PANDA_RAW_STREAM"
replace_env "CLAWDBOT_DEBUG_MEMORY_EMBEDDINGS" "PANDA_DEBUG_MEMORY_EMBEDDINGS"
replace_env "CLAWDBOT_NODE_EXEC_HOST" "PANDA_NODE_EXEC_HOST"
replace_env "CLAWDBOT_CONTROL_UI_BASE_PATH" "PANDA_CONTROL_UI_BASE_PATH"
replace_env "CLAWDBOT_ASSISTANT_NAME" "PANDA_ASSISTANT_NAME"
replace_env "CLAWDBOT_ASSISTANT_AVATAR" "PANDA_ASSISTANT_AVATAR"
replace_env "CLAWDBOT_LIVE_GATEWAY_ZAI_FALLBACK" "PANDA_LIVE_GATEWAY_ZAI_FALLBACK"
replace_env "CLAWDBOT_LIVE_GATEWAY_PROVIDERS" "PANDA_LIVE_GATEWAY_PROVIDERS"
replace_env "CLAWDBOT_LIVE_CLI_BACKEND" "PANDA_LIVE_CLI_BACKEND"
replace_env "CLAWDBOT_LIVE_CLI_BACKEND_IMAGE_PROBE" "PANDA_LIVE_CLI_BACKEND_IMAGE_PROBE"
replace_env "CLAWDBOT_LIVE_CLI_BACKEND_RESUME_PROBE" "PANDA_LIVE_CLI_BACKEND_RESUME_PROBE"
replace_env "CLAWDBOT_LIVE_MODELS" "PANDA_LIVE_MODELS"
replace_env "CLAWDBOT_LIVE_REQUIRE_PROFILE_KEYS" "PANDA_LIVE_REQUIRE_PROFILE_KEYS"
replace_env "CLAWDBOT_LIVE_SETUP_TOKEN" "PANDA_LIVE_SETUP_TOKEN"
replace_env "CLAWDBOT_LIVE_SETUP_TOKEN_VALUE" "PANDA_LIVE_SETUP_TOKEN_VALUE"
replace_env "CLAWDBOT_LIVE_SETUP_TOKEN_PROFILE" "PANDA_LIVE_SETUP_TOKEN_PROFILE"
replace_env "CLAWDBOT_LIVE_SETUP_TOKEN_MODEL" "PANDA_LIVE_SETUP_TOKEN_MODEL"
replace_env "CLAWDBOT_LIVE_BROWSER_CDP_URL" "PANDA_LIVE_BROWSER_CDP_URL"
replace_env "CLAWDBOT_TELEGRAM_ENABLE_AUTO_SELECT_FAMILY" "PANDA_TELEGRAM_ENABLE_AUTO_SELECT_FAMILY"

echo "环境变量替换完成!"
